### ISSUE TITLE
mysql npm test issue

### ISSUE THREAD

**Issue by xuqianli** [felixge/node-mysql#1010]
Hi,

I have follow the instructions on the Running integration tests from the mysql npm wiki. My node version is 0.10.36 and I have received the following error. Could you please help me to see if I am missing some setups or it is a real issue. 
```
[root@localhost node-mysql]# MYSQL_HOST=localhost MYSQL_PORT=3306 MYSQL_DATABASE=node_mysql_test MYSQL_USER=root MYSQL_PASSWORD= FILTER=integration /usr/nodebot/IBMSVT32/bin/npm test

> mysql@2.5.5 test /home/nodebot/testSteven/node-mysql
> node test/run.js

1..30
ok 1 test/integration/connection/test-bad-credentials.js
ok 2 test/integration/connection/test-bulk-insert.js
ok 3 test/integration/connection/test-connection-config-flags-affected-rows.js
ok 4 test/integration/connection/test-connection-destroy.js
ok 5 test/integration/connection/test-connection-thread-id.js
ok 6 test/integration/connection/test-insert-results.js
ok 7 test/integration/connection/test-load-data-infile.js
ok 8 test/integration/connection/test-multiple-statements-streaming.js
ok 9 test/integration/connection/test-multiple-statements-with-error.js
ok 10 test/integration/connection/test-multiple-statements.js
ok 11 test/integration/connection/test-nested-tables-query.js
ok 12 test/integration/connection/test-ping.js
ok 13 test/integration/connection/test-procedure-with-multiple-selects.js
ok 14 test/integration/connection/test-procedure-with-single-select.js
ok 15 test/integration/connection/test-query-dates-as-strings.js
ok 16 test/integration/connection/test-query-escaping.js
ok 17 test/integration/connection/test-query-escape-id.js
ok 18 test/integration/connection/test-query.js
ok 19 test/integration/connection/test-select-empty-string.js
ok 20 test/integration/connection/test-send-and-receive-large-packets.js
ok 21 test/integration/connection/test-send-and-receive-large-text.js
ok 22 test/integration/connection/test-server-timeout-disconnect.js
ok 23 test/integration/connection/test-statistics.js
not ok 24 test/integration/connection/test-timezones.js
  
  /home/nodebot/testSteven/node-mysql/lib/protocol/Parser.js:82
          throw err;
                ^
  AssertionError: "Tue Feb 24 2015 15:02:00 GMT-0500 (EST)" === "Tue Feb 24 2015 10:02:00 GMT-0500 (EST)"
      at Query._callback (/home/nodebot/testSteven/node-mysql/test/integration/connection/test-timezones.js:67:12)
      at Query.Sequence.end (/home/nodebot/testSteven/node-mysql/lib/protocol/sequences/Sequence.js:96:24)
      at Query._handleFinalResultPacket (/home/nodebot/testSteven/node-mysql/lib/protocol/sequences/Query.js:143:8)
      at Query.EofPacket (/home/nodebot/testSteven/node-mysql/lib/protocol/sequences/Query.js:127:8)
      at Protocol._parsePacket (/home/nodebot/testSteven/node-mysql/lib/protocol/Protocol.js:271:23)
      at Parser.write (/home/nodebot/testSteven/node-mysql/lib/protocol/Parser.js:77:12)
      at Protocol.write (/home/nodebot/testSteven/node-mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (/home/nodebot/testSteven/node-mysql/lib/Connection.js:82:28)
      at Socket.emit (events.js:95:17)
      at Socket.<anonymous> (_stream_readable.js:765:14)
  
ok 25 test/integration/connection/test-transaction-commit.js
ok 26 test/integration/connection/test-transaction-rollback.js
ok 27 test/integration/connection/test-type-cast-null-fields.js
ok 28 test/integration/connection/test-type-cast-query.js
ok 29 test/integration/connection/test-type-casting.js
ok 30 test/integration/connection/test-zerofill-results.js
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

**Comment by MalyshevDmitry** [comment]
I have the same issue.
Re-running tests helps for me.

**Comment by xuqianli** [comment]
by re-runing do you mean by restarting npm test again or something else ?

**Comment by MalyshevDmitry** [comment]
I mean restarting npm test again

**Comment by dougwilson** [comment]
The `test/integration/connection/test-timezones.js` test is a flaky test. If it fails, you may need to simply run the test suite again. A PR to fix this is welcome!

**Comment by xuqianli** [comment]
thank you very much for the help
really appreciate it
