### ISSUE TITLE
mysql npm test access denied questions

### ISSUE THREAD

**Issue by xuqianli** [felixge/node-mysql#1011]
Hi,

I have follow the instructions on the Running integration tests from the mysql npm wiki. My node version is 0.10.36 and I have received the following error. Could you please help me to see if I am missing some setups or it is a real issue. 
```
not ok 15 test/integration/connection/test-procedure-with-multiple-selects.js
  
  /root/testSteven/node-mysql/lib/protocol/Parser.js:82
          throw err;
                ^
  Error: ER_SPECIFIC_ACCESS_DENIED_ERROR: Access denied; you need the SUPER privilege for this operation
      at Query.Sequence._packetToError (/root/testSteven/node-mysql/lib/protocol/sequences/Sequence.js:48:14)
      at Query.ErrorPacket (/root/testSteven/node-mysql/lib/protocol/sequences/Query.js:82:18)
      at Protocol._parsePacket (/root/testSteven/node-mysql/lib/protocol/Protocol.js:271:23)
      at Parser.write (/root/testSteven/node-mysql/lib/protocol/Parser.js:77:12)
      at Protocol.write (/root/testSteven/node-mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (/root/testSteven/node-mysql/lib/Connection.js:82:28)
      at Socket.emit (events.js:95:17)
      at Socket.<anonymous> (_stream_readable.js:765:14)
      at Socket.emit (events.js:92:17)
      at emitReadable_ (_stream_readable.js:427:10)
      --------------------
      at Protocol._enqueue (/root/testSteven/node-mysql/lib/protocol/Protocol.js:135:48)
      at Connection.query (/root/testSteven/node-mysql/lib/Connection.js:185:25)
      at /root/testSteven/node-mysql/test/integration/connection/test-procedure-with-multiple-selects.js:14:14
      at Handshake._callback (/root/testSteven/node-mysql/test/common.js:109:5)
      at Handshake.Sequence.end (/root/testSteven/node-mysql/lib/protocol/sequences/Sequence.js:96:24)
      at Handshake.Sequence.OkPacket (/root/testSteven/node-mysql/lib/protocol/sequences/Sequence.js:105:8)
      at Protocol._parsePacket (/root/testSteven/node-mysql/lib/protocol/Protocol.js:271:23)
      at Parser.write (/root/testSteven/node-mysql/lib/protocol/Parser.js:77:12)
      at Protocol.write (/root/testSteven/node-mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (/root/testSteven/node-mysql/lib/Connection.js:82:28)
  
not ok 16 test/integration/connection/test-procedure-with-single-select.js
  
  /root/testSteven/node-mysql/lib/protocol/Parser.js:82
          throw err;
                ^
  Error: ER_SPECIFIC_ACCESS_DENIED_ERROR: Access denied; you need the SUPER privilege for this operation
      at Query.Sequence._packetToError (/root/testSteven/node-mysql/lib/protocol/sequences/Sequence.js:48:14)
      at Query.ErrorPacket (/root/testSteven/node-mysql/lib/protocol/sequences/Query.js:82:18)
      at Protocol._parsePacket (/root/testSteven/node-mysql/lib/protocol/Protocol.js:271:23)
      at Parser.write (/root/testSteven/node-mysql/lib/protocol/Parser.js:77:12)
      at Protocol.write (/root/testSteven/node-mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (/root/testSteven/node-mysql/lib/Connection.js:82:28)
      at Socket.emit (events.js:95:17)
      at Socket.<anonymous> (_stream_readable.js:765:14)
      at Socket.emit (events.js:92:17)
      at emitReadable_ (_stream_readable.js:427:10)
      --------------------
      at Protocol._enqueue (/root/testSteven/node-mysql/lib/protocol/Protocol.js:135:48)
      at Connection.query (/root/testSteven/node-mysql/lib/Connection.js:185:25)
      at /root/testSteven/node-mysql/test/integration/connection/test-procedure-with-single-select.js:13:14
      at Handshake._callback (/root/testSteven/node-mysql/test/common.js:109:5)
      at Handshake.Sequence.end (/root/testSteven/node-mysql/lib/protocol/sequences/Sequence.js:96:24)
      at Handshake.Sequence.OkPacket (/root/testSteven/node-mysql/lib/protocol/sequences/Sequence.js:105:8)
      at Protocol._parsePacket (/root/testSteven/node-mysql/lib/protocol/Protocol.js:271:23)
      at Parser.write (/root/testSteven/node-mysql/lib/protocol/Parser.js:77:12)
      at Protocol.write (/root/testSteven/node-mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (/root/testSteven/node-mysql/lib/Connection.js:82:28)
  
ok 17 test/integration/connection/test-query-dates-as-strings.js
ok 18 test/integration/connection/test-query-escape-id.js
ok 19 test/integration/connection/test-query-escaping.js
ok 20 test/integration/connection/test-query.js
ok 21 test/integration/connection/test-select-empty-string.js
not ok 22 test/integration/connection/test-send-and-receive-large-packets.js
  
  /root/testSteven/node-mysql/lib/protocol/Parser.js:82
          throw err;
                ^
  Error: ER_SPECIFIC_ACCESS_DENIED_ERROR: Access denied; you need the SUPER privilege for this operation
      at Query.Sequence._packetToError (/root/testSteven/node-mysql/lib/protocol/sequences/Sequence.js:48:14)
      at Query.ErrorPacket (/root/testSteven/node-mysql/lib/protocol/sequences/Query.js:82:18)
      at Protocol._parsePacket (/root/testSteven/node-mysql/lib/protocol/Protocol.js:271:23)
      at Parser.write (/root/testSteven/node-mysql/lib/protocol/Parser.js:77:12)
      at Protocol.write (/root/testSteven/node-mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (/root/testSteven/node-mysql/lib/Connection.js:82:28)
      at Socket.emit (events.js:95:17)
      at Socket.<anonymous> (_stream_readable.js:765:14)
      at Socket.emit (events.js:92:17)
      at emitReadable_ (_stream_readable.js:427:10)
      --------------------
      at Protocol._enqueue (/root/testSteven/node-mysql/lib/protocol/Protocol.js:135:48)
      at Connection.query (/root/testSteven/node-mysql/lib/Connection.js:185:25)
      at increaseMaxAllowedPacketIfNeeded (/root/testSteven/node-mysql/test/integration/connection/test-send-and-receive-large-packets.js:32:14)
      at Query._callback (/root/testSteven/node-mysql/test/integration/connection/test-send-and-receive-large-packets.js:19:5)
      at Query.Sequence.end (/root/testSteven/node-mysql/lib/protocol/sequences/Sequence.js:96:24)
      at Query._handleFinalResultPacket (/root/testSteven/node-mysql/lib/protocol/sequences/Query.js:143:8)
      at Query.EofPacket (/root/testSteven/node-mysql/lib/protocol/sequences/Query.js:127:8)
      at Protocol._parsePacket (/root/testSteven/node-mysql/lib/protocol/Protocol.js:271:23)
      at Parser.write (/root/testSteven/node-mysql/lib/protocol/Parser.js:77:12)
      at Protocol.write (/root/testSteven/node-mysql/lib/protocol/Protocol.js:39:16)
  
ok 23 test/integration/connection/test-server-timeout-disconnect.js
not ok 24 test/integration/connection/test-send-and-receive-large-text.js
  
  /root/testSteven/node-mysql/lib/protocol/Parser.js:82
          throw err;
                ^
  Error: ER_SPECIFIC_ACCESS_DENIED_ERROR: Access denied; you need the SUPER privilege for this operation
      at Query.Sequence._packetToError (/root/testSteven/node-mysql/lib/protocol/sequences/Sequence.js:48:14)
      at Query.ErrorPacket (/root/testSteven/node-mysql/lib/protocol/sequences/Query.js:82:18)
      at Protocol._parsePacket (/root/testSteven/node-mysql/lib/protocol/Protocol.js:271:23)
      at Parser.write (/root/testSteven/node-mysql/lib/protocol/Parser.js:77:12)
      at Protocol.write (/root/testSteven/node-mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (/root/testSteven/node-mysql/lib/Connection.js:82:28)
      at Socket.emit (events.js:95:17)
      at Socket.<anonymous> (_stream_readable.js:765:14)
      at Socket.emit (events.js:92:17)
      at emitReadable_ (_stream_readable.js:427:10)
      --------------------
      at Protocol._enqueue (/root/testSteven/node-mysql/lib/protocol/Protocol.js:135:48)
      at Connection.query (/root/testSteven/node-mysql/lib/Connection.js:185:25)
      at increaseMaxAllowedPacketIfNeeded (/root/testSteven/node-mysql/test/integration/connection/test-send-and-receive-large-text.js:32:14)
      at Query._callback (/root/testSteven/node-mysql/test/integration/connection/test-send-and-receive-large-text.js:19:5)
      at Query.Sequence.end (/root/testSteven/node-mysql/lib/protocol/sequences/Sequence.js:96:24)
      at Query._handleFinalResultPacket (/root/testSteven/node-mysql/lib/protocol/sequences/Query.js:143:8)
      at Query.EofPacket (/root/testSteven/node-mysql/lib/protocol/sequences/Query.js:127:8)
      at Protocol._parsePacket (/root/testSteven/node-mysql/lib/protocol/Protocol.js:271:23)
      at Parser.write (/root/testSteven/node-mysql/lib/protocol/Parser.js:77:12)
      at Protocol.write (/root/testSteven/node-mysql/lib/protocol/Protocol.js:39:16)
```

**Comment by dougwilson** [comment]
Those tests simply require that the user you are using to do the tests have the `SUPER privilege` set in your db grants.

**Comment by xuqianli** [comment]
i am accessing as root user and also i installed the mysql server using root account. What else do i need to setup for the access grant?

**Comment by dougwilson** [comment]
The answer over at http://stackoverflow.com/questions/11946012/how-to-add-super-privileges-to-mysql-database should help; it provides the way through phpmyadmin or what SQL you need to execute on the console (change the user, host, and pass to match what you need, of course)

**Comment by xuqianli** [comment]
thanks
