### ISSUE TITLE
mysql npm test assertionError question

### ISSUE THREAD

**Issue by xuqianli** [felixge/node-mysql#1012]
Hi,

I have follow the instructions on the Running integration tests from the mysql npm wiki. My node version is 0.10.36 and I have received the following error. Could you please help me to see if I am missing some setups or it is a real issue.
```
not ok 26 test/integration/connection/test-timezones.js
  
  /root/testSteven/node-mysql/lib/protocol/Parser.js:82
          throw err;
                ^
  AssertionError: "Tue Feb 24 2015 15:25:00 GMT-0500 (EST)" === "Tue Feb 24 2015 10:25:00 GMT-0500 (EST)"
      at Query._callback (/root/testSteven/node-mysql/test/integration/connection/test-timezones.js:67:12)
      at Query.Sequence.end (/root/testSteven/node-mysql/lib/protocol/sequences/Sequence.js:96:24)
      at Query._handleFinalResultPacket (/root/testSteven/node-mysql/lib/protocol/sequences/Query.js:143:8)
      at Query.EofPacket (/root/testSteven/node-mysql/lib/protocol/sequences/Query.js:127:8)
      at Protocol._parsePacket (/root/testSteven/node-mysql/lib/protocol/Protocol.js:271:23)
      at Parser.write (/root/testSteven/node-mysql/lib/protocol/Parser.js:77:12)
      at Protocol.write (/root/testSteven/node-mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (/root/testSteven/node-mysql/lib/Connection.js:82:28)
      at Socket.emit (events.js:95:17)
      at Socket.<anonymous> (_stream_readable.js:765:14)
```

**Comment by dougwilson** [comment]
The `test/integration/connection/test-timezones.js` test is a flaky test and can fail even if there is no issue. A PR to help make that test more reliable is welcome!
