### ISSUE TITLE
mysql npm test ER_HOST_NOT_PRIVILEGED questions

### ISSUE THREAD

**Issue by xuqianli** [felixge/node-mysql#1013]
Hi,
I have started the mysql server through root user but I wish to access it from other hosts. Is there anything I should setup to grant the privilege for other hosts other than the localhosts?

thank you very much 
```
not ok 2 test/integration/connection/test-bulk-insert.js
  /home/nodebot/testSteven/node-mysql/lib/protocol/Parser.js:82
          throw err;
                ^
  Error: ER_HOST_NOT_PRIVILEGED: Host 'jtcjs08.hursley.ibm.com' is not allowed to connect to this MySQL server
      at Handshake.Sequence._packetToError (/home/nodebot/testSteven/node-mysql/lib/protocol/sequences/Sequence.js:48:14)
      at Handshake.ErrorPacket (/home/nodebot/testSteven/node-mysql/lib/protocol/sequences/Handshake.js:101:18)
      at Protocol._parsePacket (/home/nodebot/testSteven/node-mysql/lib/protocol/Protocol.js:271:23)
      at Parser.write (/home/nodebot/testSteven/node-mysql/lib/protocol/Parser.js:77:12)
      at Protocol.write (/home/nodebot/testSteven/node-mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (/home/nodebot/testSteven/node-mysql/lib/Connection.js:82:28)
      at Socket.emit (events.js:107:17)
      at readableAddChunk (_stream_readable.js:163:16)
      at Socket.Readable.push (_stream_readable.js:126:10)
      at TCP.onread (net.js:529:20)
      --------------------
      at Protocol._enqueue (/home/nodebot/testSteven/node-mysql/lib/protocol/Protocol.js:135:48)
      at Protocol.handshake (/home/nodebot/testSteven/node-mysql/lib/protocol/Protocol.js:52:41)
      at Connection.connect (/home/nodebot/testSteven/node-mysql/lib/Connection.js:109:18)
      at Object.getTestConnection (/home/nodebot/testSteven/node-mysql/test/common.js:95:14)
      at Object.<anonymous> (/home/nodebot/testSteven/node-mysql/test/integration/connection/test-bulk-insert.js:6:8)
      at Module._compile (module.js:460:26)
      at Object.Module._extensions..js (module.js:478:10)
      at Module.load (module.js:355:32)
      at Function.Module._load (module.js:310:12)
      at Function.Module.runMain (module.js:501:10)
```

**Comment by ravi** [comment]
This is a MySQL issue. See: http://dev.mysql.com/doc/refman/5.1/en/connection-access.html for some information that might help.

**Comment by dougwilson** [comment]
Yes, this is beyond the scope of this module. Basically you just need to configure your user permissions, which is a basic task of MySQL server maintenance.
