### ISSUE TITLE
TypeError: Cannot read property 'query' of undefined

### ISSUE THREAD

**Issue by wormen** [felixge/node-mysql#1024]
error text
```
/node_www/crawler.x-sells.com/node_modules/mysql/lib/protocol/Parser.js:82
        throw err;
              ^
TypeError: Cannot read property 'query' of undefined
    at /node_www/crawler.x-sells.com/autoInit.js:53:19
    at Handshake.onConnect (/node_www/crawler.x-sells.com/node_modules/mysql/lib/Pool.js:54:9)
    at Handshake.Sequence.end (/node_www/crawler.x-sells.com/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Handshake.ErrorPacket (/node_www/crawler.x-sells.com/node_modules/mysql/lib/protocol/sequences/Handshake.js:103:8)
    at Protocol._parsePacket (/node_www/crawler.x-sells.com/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/node_www/crawler.x-sells.com/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/node_www/crawler.x-sells.com/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/node_www/crawler.x-sells.com/node_modules/mysql/lib/Connection.js:82:28)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:529:20)
```
windows on everything works fine, but when you transfer linux appears this error
tell me how it is solved

**Comment by dougwilson** [comment]
It really depends on what your code in the `/node_www/crawler.x-sells.com/autoInit.js` file is.

**Comment by dougwilson** [comment]
Most likely you have code like
```js
pool.getConnection(function (err, conn) {
  conn.query(/* ... */);
})
```
which is not correct, because you never checked and acted on `err`.

**Comment by wormen** [comment]
@dougwilson No, the connection I have so

mysql.createPool({
             connectionLimit : $config.get('db:connectionLimit'),
             host      : $config.get('db:host'),
             user      : $config.get('db:user'),
             database  : $config.get('db:base'),
             password  : $config.get('db:password')
         })

using so

db.getConnection(function (err, connection) {
            connection.query(/* ... */, [], callback);
            connection.release();
        });

but the problem is this only in Linux, and it is not always

**Comment by dougwilson** [comment]
Thanks :) Your second code block is incorrect. It should be as follows:
```js
db.getConnection(function (err, connection) {
      if (err) throw err; // You *MUST* handle err and not continue execution if
                          // there is an error. this is a standard part of Node.js
            connection.query(/* ... */, [], callback);
            connection.release();
        });
```
