### ISSUE TITLE
Can't establish connection to local database when not connected to the Internet on Windows

### ISSUE THREAD

**Issue by mattecapu** [felixge/node-mysql#1030]
Hi,
When my PC is not connected to the Internet, `node-mysql` fails to connect to my local database. Other tools like phpMyAdmin have no problem establishing a connection in the same conditions, and when I'm connected to the Internet all works fine.
Here's the stacktrace of the error:
```
 Error: getaddrinfo ENOENT
   at Object.exports._errnoException (util.js:746:11)
   at errnoException (dns.js:49:15)
   at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
   --------------------
   at Protocol._enqueue (D:\www\carpenter\node_modules\mysql\lib\protocol\Protocol.js:135:48)
   at Protocol.handshake (D:\www\carpenter\node_modules\mysql\lib\protocol\Protocol.js:52:41)
   at Connection.connect (D:\www\carpenter\node_modules\mysql\lib\Connection.js:109:18)
```
I can't find any similar case on Google, so maybe is my installation (or my workstation) that is broken.

**Comment by adrianblynch** [comment]
How are you addressing your DB, localhost? Looks like it might be a DNS issue. Namely, no internet connection, no DNS.

**Comment by dougwilson** [comment]
It's unfortunate, but Node.js seems to use a different resolver than other programs. If you have the host as "localhost" have you tried using "127.0.0.1"?

**Comment by mattecapu** [comment]
@dougwilson that fixed the issue, thank you

**Comment by ntepp** [comment]
Thank.
