### ISSUE TITLE
Pool does not exist error after mysql services restarted.

### ISSUE THREAD

**Issue by rabbitfufu** [felixge/node-mysql#1041]
Hello,

I am using poolCluster.  

It works great, unless I reboot mysql or restart the mysql services.  Then poolcluster seems to break, and returns the error "Pool does not exist".  If I restart my node application, everything works fine again.

```
app (err):     at PoolCluster._getConnection (/home/ssp/node_modules/mysql/lib/PoolCluster.js:151:13)
app (err):     at PoolNamespace.getConnection (/home/ssp/node_modules/mysql/lib/PoolCluster.js:190:11)
app (err):     at /home/ssp/node_modules/mysql/lib/PoolCluster.js:195:24
app (err):     at /home/ssp/node_modules/mysql/lib/PoolCluster.js:154:7
app (err):     at Handshake.onConnect (/home/ssp/node_modules/mysql/lib/Pool.js:54:9)
app (err):     at Handshake.Sequence.end (/home/ssp/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
app (err): Error: connect EHOSTUNREACH
app (err):     at exports._errnoException (util.js:746:11)
app (err):     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:19)
app (err):     --------------------
app (err):     at Protocol._enqueue (/home/ssp/node_modules/mysql/lib/protocol/Protocol.js:135:48)
app (err):     at Protocol.handshake (/home/ssp/node_modules/mysql/lib/protocol/Protocol.js:52:41)
app (err):     at PoolConnection.connect (/home/ssp/node_modules/mysql/lib/Connection.js:109:18)
app (err):     at Pool.getConnection (/home/ssp/node_modules/mysql/lib/Pool.js:45:23)
app (err):     at PoolCluster._getConnection (/home/ssp/node_modules/mysql/lib/PoolCluster.js:151:13)
app (err):     at PoolNamespace.getConnection (/home/ssp/node_modules/mysql/lib/PoolCluster.js:190:11)
app (err):     at /home/ssp/node_modules/mysql/lib/PoolCluster.js:195:24
app (err):     at /home/ssp/node_modules/mysql/lib/PoolCluster.js:154:7
app (err):     at Handshake.onConnect (/home/ssp/node_modules/mysql/lib/Pool.js:54:9)
app (err):     at Handshake.Sequence.end (/home/ssp/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
```
Could anyone shed some light on this, and offer any suggestions on how to fix this problem?

Thank-you!

**Comment by dougwilson** [comment]
This is because in `PoolCluster`, after you reach `removeNodeErrorCount` errors in a row (defaults to 5), then the server is completely removed. What it sounds like is you need to set the `restoreNodeTimeout` option so after a while, the cluster will once again attempt to connect.

You can read more about the options at https://github.com/felixge/node-mysql#poolcluster-option

**Comment by rabbitfufu** [comment]
Thanks for the quick response -- I'll experiment with this

**Comment by adrianblynch** [comment]
@rabbitfufu - Did you get anywhere with this? I'm working on the same problem.

**Comment by dougwilson** [comment]
Closing due to lack of response or activity. Please feel free to post back here and I can always reopen :)
