### ISSUE TITLE
PROTOCOL_PACKETS_OUT_OF_ORDER

### ISSUE THREAD

**Issue by charlitos85** [felixge/node-mysql#1056]
Sometimes i receive this error with a query.
```
{ [Error: Packets out of order. Got: 65 Expected: 216] code: 'PROTOCOL_PACKETS_OUT_OF_ORDER', fatal: true }
```
this is the debug log:
```
  serverVersion: '5.1.73',

<-- RowDataPacket
{ id_customer: 1853,
  id_sale: 4,
  id_right: 3,
  company_name: 'zzz aa ANiudad',
  address: 'la,lala>\u0000\u0000�\u00041274\u00017\u00013\u000fabc def$zzz 691,xxx,xxxH\u0000\u0000�\u00041275\u00011\u00013\u001cCIQABR' }

{ [Error: Packets out of order. Got: 36 Expected: 195] code: 'PROTOCOL_PACKETS_OUT_OF_ORDER', fatal: true }
```
in node 0.10.35 x64 and mysql 2.6.1

**Comment by dougwilson** [comment]
Thanks for the report! Unfortunately there is not enough information posted above to do anything with. The best way to help would be to post the _full_ debug log, rather than just the last few lines, because there isn't much context. Another thing that can help us is if you can distill causing the error into a tiny `.js` file I can run, which also helps us know what methods you are calling in what order as well for this to occur.

**Comment by dougwilson** [comment]
Hi @charlitos85 any update?

**Comment by tvollstaedt** [comment]
Hi, i've also got this error in a earlier version (node-mysql 2.6.2) when inserting a big dataset (160.000 records). Now after an update to node-mysql 2.8.0, the same query returns an ```ER_NET_PACKAGE_TOO_LARGE``` which means the query is too big for the server to process. You may need to increase ```max_allowed_packet``` in your server config to avoid this issue.

**Comment by dougwilson** [comment]
Ah, thanks, @tvollstaedt ! If you were getting `PROTOCOL_PACKETS_OUT_OF_ORDER` for the same reason as @charlitos85 (it's hard to know, since there was never an update), and now the error changed to something that makes sense, it's certainly possible we've fixed the underlying error :)

**Comment by metrue** [comment]
Get same error here, 
```
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error: Packets out of order. Got: 1 Expected: 2
    at Parser._tryReadPacketHeader (/Users/minhuang/Code/mysql_http/node_modules/mysql/lib/protocol/Parser.js:470:15)
    at Parser.write (/Users/minhuang/Code/mysql_http/node_modules/mysql/lib/protocol/Parser.js:33:29)
    at Protocol.write (/Users/minhuang/Code/mysql_http/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/minhuang/Code/mysql_http/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/minhuang/Code/mysql_http/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:312:12)
    at readableAddChunk (node:internal/streams/readable:287:9)
    at Socket.Readable.push (node:internal/streams/readable:226:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    --------------------
    at Protocol._enqueue (/Users/minhuang/Code/mysql_http/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/minhuang/Code/mysql_http/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/Users/minhuang/Code/mysql_http/node_modules/mysql/lib/Connection.js:116:18)
    at /Users/minhuang/Code/mysql_http/write_multi_thread.js:87:20
    at new Promise (<anonymous>)
    at connect (/Users/minhuang/Code/mysql_http/write_multi_thread.js:86:14)
    at handle (/Users/minhuang/Code/mysql_http/write_multi_thread.js:97:11)
    at Worker.<anonymous> (/Users/minhuang/Code/mysql_http/write_multi_thread.js:26:23)
    at Worker.emit (node:events:406:35)
    at ChildProcess.<anonymous> (node:internal/cluster/worker:33:12) {
  code: 'PROTOCOL_PACKETS_OUT_OF_ORDER',
  fatal: true
}
```
