### ISSUE TITLE
mysql/lib/protocol/SqlString.js:71 TypeError: undefined is not a function

### ISSUE THREAD

**Issue by reggi** [felixge/node-mysql#1058]
```
/Users/thomas/Desktop/project/node_modules/mysql/lib/protocol/SqlString.js:71
  return sql.replace(/\?\??/g, function(match) {
             ^
TypeError: undefined is not a function
    at Object.SqlString.format (/Users/thomas/Desktop/wordpress-shopify-importer/node_modules/mysql/lib/protocol/SqlString.js:71:14)
    at Connection.format (/Users/thomas/Desktop/wordpress-shopify-importer/node_modules/mysql/lib/Connection.js:247:20)
    at Connection.query (/Users/thomas/Desktop/wordpress-shopify-importer/node_modules/mysql/lib/Connection.js:183:20)
    at Object.<anonymous> (/Users/thomas/Desktop/wordpress-shopify-importer/index.js:14:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:428:10)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
    at Function.Module.runMain (module.js:451:10)
    at startup (node.js:124:18)
```

**Comment by dougwilson** [comment]
Hi! Can you provide a little simple program or some code to reproduce? It looks like it's caused by a bad call into this library.

**Comment by dougwilson** [comment]
Mainly what is on line 14 in wordpress-shopify-importer/index.js ?

**Comment by reggi** [comment]
This is all I've got. I was trying to hide what I was working on. Whoops.

```
var mysql = require('mysql')
var options = {
  host: process.env.MYSQL_HOST,
  user: process.env.MYSQL_USER,
  password: process.env.MYSQL_PASSWORD,
  database: process.env.MYSQL_DATABASE,
  charset: "utf8"
}

var connection = mysql.createConnection(options)

connection.connect()

connection.query(function(err, rows, fields) {
  if (err) throw err
  console.log(rows.length)
});

connection.end()

```

**Comment by reggi** [comment]
No query, duh.

**Comment by dougwilson** [comment]
lol, thanks. Looks like our arguments are probably too forgiving, haha, because we should probably throw a useful error on a missing query ;)
