### ISSUE TITLE
Object has no method 'apply'

### ISSUE THREAD

**Issue by jhiver** [felixge/node-mysql#1060]
Hello, and thanks for your library. Please help me understand this error.... I have this really simple query makes my app crash:

        <snip...>
        # This is the test record that we have imported:
	# INSERT INTO portal_users (email, encrypted_password) VALUES ('jhiver@gmail.com', 'c3ab8ff13720e8ad9047dd39466b3c8974e592c2fa383d4a3960714caef0c4f2');
	mysql.query 'SELECT * FROM portal_users WHERE email=? AND encrypted_password=?', user, hash, (error, results) ->
		if error then return res.sendError 500, error
		return res.sendResult results

Here's the error message:

		TypeError: Object e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 has no method 'apply'
		  at Query.Sequence.end (/Users/jhiver/api.life/anemone/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
		  at Query.ErrorPacket (/Users/jhiver/api.life/anemone/server/node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
		  at Protocol._parsePacket (/Users/jhiver/api.life/anemone/server/node_modules/mysql/lib/protocol/Protocol.js:271:23)
		  at Parser.write (/Users/jhiver/api.life/anemone/server/node_modules/mysql/lib/protocol/Parser.js:77:12)
		  at Protocol.write (/Users/jhiver/api.life/anemone/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)
		  at Socket.<anonymous> (/Users/jhiver/api.life/anemone/server/node_modules/mysql/lib/Connection.js:92:28)
		  at Socket.emit (events.js:95:17)
		  at Socket.<anonymous> (_stream_readable.js:765:14)
		  at Socket.emit (events.js:92:17)
		  at emitReadable_ (_stream_readable.js:427:10)
		  at emitReadable (_stream_readable.js:423:5)
		  at readableAddChunk (_stream_readable.js:166:9)
		  at Socket.Readable.push (_stream_readable.js:128:10)
		  at TCP.onread (net.js:529:21)

And finally the (very simple) table definition:

		CREATE TABLE `portal_users` (
		  `id` int(11) NOT NULL AUTO_INCREMENT,
		  `email` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
		  `encrypted_password` varchar(128) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
		  PRIMARY KEY (`id`),
		  UNIQUE KEY `index_users_on_email` (`email`)
		) ENGINE=MyISAM AUTO_INCREMENT=898 DEFAULT CHARSET=latin1;

Any clues about what's happening here?

Thanks
JM

**Comment by AdriVanHoudt** [comment]
try passing the values as an array `[user, hash]`

**Comment by jhiver** [comment]
*slaps head* - thank you so much!

**Comment by AdriVanHoudt** [comment]
no problem, close the issue if it's fixed

**Comment by dougwilson** [comment]
Thanks for helping, @AdriVanHoudt ! I appreciate it :) I'm going to re-open the bug for now so I can remember that I should add more argument validation to the `.query()` method so the failure is early and easier to understand ;)

**Comment by AdriVanHoudt** [comment]
np and good idea!
