### ISSUE TITLE
Error: Handshake inactivity timeout

### ISSUE THREAD

**Issue by ezekel** [felixge/node-mysql#1106]
I am getting this error, I don't know what causes this to generate this errors.

Thank you in advance.
```
    at Handshake.<anonymous> (C:\wamp\www\newsite\node_modules\mysql\lib\protoc
ol\Protocol.js:154:17)
    at Handshake.emit (events.js:104:17)
    at Handshake._onTimeout (C:\wamp\www\newsite\node_modules\mysql\lib\protoco
l\sequences\Sequence.js:116:8)
    at Timer.listOnTimeout (timers.js:110:15)
    --------------------
    at Protocol._enqueue (C:\wamp\www\newsite\node_modules\mysql\lib\protocol\P
rotocol.js:135:48)
    at Protocol.handshake (C:\wamp\www\newsite\node_modules\mysql\lib\protocol\
Protocol.js:52:41)
    at PoolConnection.connect (C:\wamp\www\newsite\node_modules\mysql\lib\Conne
ction.js:119:18)
    at Pool.getConnection (C:\wamp\www\newsite\node_modules\mysql\lib\Pool.js:4
5:23)
    at Pool.releaseConnection (C:\wamp\www\newsite\node_modules\mysql\lib\Pool.
js:135:10)
    at Pool._removeConnection (C:\wamp\www\newsite\node_modules\mysql\lib\Pool.
js:247:8)
    at Pool._purgeConnection (C:\wamp\www\newsite\node_modules\mysql\lib\Pool.j
s:228:8)
```

```javascript 
var pool = mysql.createPool({

    host: 'localhost',
    user: 'root',
    password: '',
    dateStrings: true,
    database: 'mydb'


});


 socket.on('getdata1',function(data){
        pool.getConnection(function (err, connection) {
                    if (err) {
                        console.error('error connecting: ' + err.stack);

                    }
			        connection.query(options, [devid, logid], function (err, results) {

                            if (err) {
                                console.log(err);
                               
                            }


                            socket.emit('getpost', results);
                            connection.release();
                        });

          });	
   });		  


```

**Comment by dougwilson** [comment]
The error "Error: Handshake inactivity timeout" occurs when this module tries to connect to your MySQL server, the TCP connection is established, but the MySQL server does not respond in a timely manner (defaults to 10 seconds). If your MySQL is taking longer than 10 seconds, there is probably something serious going on on your server.

You can always adjust this timeout using the `acquireTimeout` in the `mysql.createPool` if you really want (but I don't recommend it).

**Comment by ezekel** [comment]
Thank you for the quick reply.
