### ISSUE TITLE
Handshake.ErrorPacket  error every 100k requests

### ISSUE THREAD

**Issue by x25** [felixge/node-mysql#1128]
Error:

```
at Handshake.ErrorPacket (/var/www/app/node_modules/mysql/lib/protocol/sequences/Handshake.js:101:18)
at Protocol._parsePacket (/var/www/app/node_modules/mysql/lib/protocol/Protocol.js:271:23)
at Parser.write (/var/www/app/node_modules/mysql/lib/protocol/Parser.js:77:12)
at Protocol.write (/var/www/app/node_modules/mysql/lib/protocol/Protocol.js:39:16)
at Socket.<anonymous> (/var/www/app/node_modules/mysql/lib/Connection.js:92:28)
at Socket.EventEmitter.emit (events.js:95:17)
at Socket.<anonymous> (_stream_readable.js:746:14)
at Socket.EventEmitter.emit (events.js:92:17)
at emitReadable_ (_stream_readable.js:408:10)
--------------------
at Protocol._enqueue (/var/www/app/node_modules/mysql/lib/protocol/Protocol.js:135:48)
at Protocol.handshake (/var/www/app/node_modules/mysql/lib/protocol/Protocol.js:52:41)
at PoolConnection.connect (/var/www/app/node_modules/mysql/lib/Connection.js:119:18)
at Pool.getConnection (/var/www/app/node_modules/mysql/lib/Pool.js:45:23)
at Pool.releaseConnection (/var/www/app/node_modules/mysql/lib/Pool.js:135:10)
at Pool._removeConnection (/var/www/app/node_modules/mysql/lib/Pool.js:247:8)
at PoolConnection._removeFromPool (/var/www/app/node_modules/mysql/lib/PoolConnection.js:61:8)
at PoolConnection.EventEmitter.emit (events.js:95:17)
at PoolConnection.Connection._handleProtocolError (/var/www/app/node_modules/mysql/lib/Connection.js:372:8)
at Protocol.EventEmitter.emit (events.js:95:17)
```

```bash
$ node -v
v0.10.25
```

```bash
$ npm list mysql
app@0.0.1 /var/www/app
└── mysql@2.6.2
```

**Comment by dougwilson** [comment]
Hi! That for the stack trace, though that line is just where it turns an error pack from your MySQL server into a JS Error object, so the stack trace does not help, unfortunately. Can you post the error message?

**Comment by x25** [comment]
*ER_CON_COUNT_ERROR: Too many connections*

I use the pool:

```js
mysql.createPool({
		connectionLimit : 3,
		host: ...,
		user: ...,
		password: ...,
		database: ...
});
```

That's what I see in the mysql process list:

```
+------+------+-----------------+------+---------+------+-------+------------------+
| Id   | User | Host            | db   | Command | Time | State | Info             |
+------+------+-----------------+------+---------+------+-------+------------------+
| 2532 | user | localhost:44665 | r1   | Sleep   |  668 |       | NULL             |
| 2537 | user | localhost:44674 | r1   | Sleep   |  670 |       | NULL             |
| 2538 | user | localhost:44675 | r1   | Sleep   |  449 |       | NULL             |
| 2543 | user | localhost:46070 | r1   | Sleep   |  593 |       | NULL             |
| 2544 | user | localhost:46071 | r1   | Sleep   |  549 |       | NULL             |
| 2545 | user | localhost:46078 | r1   | Sleep   |  593 |       | NULL             |
| 2546 | user | localhost:46079 | r1   | Sleep   |  582 |       | NULL             |
| 2547 | user | localhost:46080 | r1   | Sleep   |  549 |       | NULL             |
| 2548 | user | localhost:46081 | r1   | Sleep   |  525 |       | NULL             |
| 2549 | user | localhost:46082 | r1   | Sleep   |  419 |       | NULL             |
| 2550 | user | localhost:46083 | r1   | Sleep   |  452 |       | NULL             |
| 2551 | user | localhost:46084 | r1   | Sleep   |  452 |       | NULL             |
| 2552 | user | localhost:46085 | r1   | Sleep   |  387 |       | NULL             |
| 2553 | user | localhost:46086 | r1   | Sleep   |  434 |       | NULL             |
...
| 2567 | user | localhost:46102 | r1   | Sleep   |   42 |       | NULL             |
| 2568 | user | localhost       | NULL | Query   |    0 | NULL  | show processlist |
...
| 2572 | user | localhost:46106 | r1   | Sleep   |    0 |       | NULL             |
| 2573 | user | localhost:46107 | r1   | Sleep   |    3 |       | NULL             |
| 2574 | user | localhost:46108 | r1   | Sleep   |    1 |       | NULL             |
+------+------+-----------------+------+---------+------+-------+------------------+
35 rows in set (0.00 sec)
```

There is no other process using this mysql server and the number of connections grows.

**Comment by dougwilson** [comment]
There is a fix in 2.7.0 that may help here. Have you tried 2.7.0 yet?

**Comment by x25** [comment]
Yep, in 2.7.0 its ok. Thanks!

**Comment by dougwilson** [comment]
Cool, I'm glad to hear!
