### ISSUE TITLE
pool cluster's on is not exist.

### ISSUE THREAD

**Issue by breaklee** [felixge/node-mysql#1161]
i'm trying pool cluster of mysql module.

below is my stub code.

and i created pool cluster, and get pool using of('namespace');

but there are wpool's on function is not exist ( ERROR )

how can is use this?
====================================================

var wpool = poolCluster.of('MASTER-01', 'ORDER');//RANDOM, 
var rpool = poolCluster.of('SLAVE-*', 'ORDER');

wpool.on('connection', function (connection) {
	connection.query('USE muscat');	
	connection.query('SET SESSION auto_increment_increment=1');
	queryFormat(connection);
});
====================================================

wpool.on('connection', function (connection) {
      ^
TypeError: undefined is not a function
    at Object.<anonymous> (/Users/breaklee/Documents/project/eazler/muscat/database/mysql.js:32:7)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/breaklee/Documents/project/eazler/muscat/database/index.js:4:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by dougwilson** [comment]
Unfortunately `poolCluster.of` does not return a `Pool` object, but rather a `PoolNamespace` object, which is not an event emitter. Sadly, the way to do what you're looking for was never implemented yet, so to get the `connection` listener, we would have to say "you're welcome to make a pull request implementing this feature" right now.
