### ISSUE TITLE
pool connection error

### ISSUE THREAD

**Issue by Ting-y** [felixge/node-mysql#1183]
Error will pop up after the 8th or 9th call of the `uodateUser` function.

Any idea for this error?

In my code:
```js

var mysqlPool = mysql.createPool({
    host: config.mysql.host,
    user: config.mysql.user,
    password: config.mysql.password,
    database: config.mysql.database,
    connectionLimit: 100,
    connectTimeout: 2000,
    queueLimit: 0,
    debug: true,
    waitForConnection: true,
    dateStrings: true
});


   updateUser: function (data, row, callback) {

        var query, promise;
        query = "UPDATE user SET ? where row_id = ?";

        mysqlPool.getConnection(function (err, connection) {
            if (err) {
                connection.release();
                throw err;
            }
            connection.query(query,[data, row], function (err, result) {
                connection.release();
                if (err) {
                    callback(err, bull );
                } else {
                    callback(null, result);
                }
            });
        });
    }

```

```
/home/ting-y/sandbox/location-exception/db.js:74
                connection.release();
                          ^
TypeError: Cannot read property 'release' of undefined
    at /home/ting-y/sandbox/location-exception/db.js:74:27
    at Handshake.onConnect (/home/ting-y/sandbox/location-exception/node_modules/mysql/lib/Pool.js:54:9)
    at Handshake.Sequence.end (/home/ting-y/sandbox/location-exception/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Protocol.handleNetworkError (/home/ting-y/sandbox/location-exception/node_modules/mysql/lib/protocol/Protocol.js:358:14)
    at PoolConnection.Connection._handleNetworkError (/home/ting-y/sandbox/location-exception/node_modules/mysql/lib/Connection.js:382:18)
    at PoolConnection.Connection._handleConnectTimeout (/home/ting-y/sandbox/location-exception/node_modules/mysql/lib/Connection.js:378:8)
    at Socket.g (events.js:199:16)
    at Socket.emit (events.js:104:17)
    at Socket._onTimeout (net.js:348:8)
    at _makeTimerTimeout (timers.js:476:11)
```

**Comment by dougwilson** [comment]
Hi! So the issue is just a small fix needed to your code for the error you are getting. The traditional callback function always takes an error as the first argument, and then n arguments after full of data. For `mysqlPool.getConnection`, the method's callback takes `err` and `connection`.

Now, the traditional style is that if `err` is not defined, all the other arguments are defined, but if `err` is defined, then _none of the other arguments are defined_. This means that when you have `err` defined, then `connection` is not defined, thus your error.

Your code can be altered to the following:
```js
   updateUser: function (data, row, callback) {

        var query, promise;
        query = "UPDATE user SET ? where row_id = ?";

        mysqlPool.getConnection(function (err, connection) {
            if (err) {
                // connection.release(); <-- this line is in error, as if there was an error getting a connection, then you won't have a connection to release
                throw err;
            }
            connection.query(query,[data, row], function (err, result) {
                connection.release();
                if (err) {
                    callback(err, bull );
                } else {
                    callback(null, result);
                }
            });
        });
    }
```

**Comment by Ting-y** [comment]
After remove the connection.release line, it still have the get connection ETIMEDOUT error
```
/home/ting-y/sandbox/location-exception/db.js:72
                throw err;
                      ^
Error: connect ETIMEDOUT
    at PoolConnection.Connection._handleConnectTimeout (/home/ting-y/sandbox/location-exception/node_modules/mysql/lib/Connection.js:373:13)
    at Socket.g (events.js:199:16)
    at Socket.emit (events.js:104:17)
    at Socket._onTimeout (net.js:348:8)
    at _makeTimerTimeout (timers.js:476:11)
    at Timer.unrefTimeout (timers.js:540:5)
    --------------------
    at Protocol._enqueue (/home/ting-y/sandbox/location-exception/node_modules/mysql/lib/protocol/Protocol.js:135:48)
    at Protocol.handshake (/home/ting-y/sandbox/location-exception/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at PoolConnection.connect (/home/ting-y/sandbox/location-exception/node_modules/mysql/lib/Connection.js:123:18)
    at Pool.getConnection (/home/ting-y/sandbox/location-exception/node_modules/mysql/lib/Pool.js:45:23)
    at module.exports.updateTransaction (/home/ting-y/sandbox/location-exception/db.js:70:19)
    at /home/ting-y/sandbox/location-exception/node_modules/promise/lib/node-extensions.js:24:20
    at tryCallTwo (/home/ting-y/sandbox/location-exception/node_modules/promise/lib/core.js:45:5)
    at doResolve (/home/ting-y/sandbox/location-exception/node_modules/promise/lib/core.js:171:13)
    at new Promise (/home/ting-y/sandbox/location-exception/node_modules/promise/lib/core.js:65:3)
    at /home/ting-y/sandbox/location-exception/node_modules/promise/lib/node-extensions.js:19:12
```

**Comment by dougwilson** [comment]
Hi @Ting-y ! Unfortunately that error I can't really help with :(  The stack trace is that the pool tried to establish a brand new TCP connection to your MySQL server, the connect was established, then we send the initial MySQL handshake packet, but never got a response from your MySQL server after waiting 10 seconds.

This is usually some issue on your network on MySQL server, both of witch would have to be investigated.

If you think your server just takes longer than 10 seconds to response, you can always increase the timeout by altering the `acquireTimeout` option in your `createPool` call (see https://github.com/felixge/node-mysql#pool-options for a list of pool-related options).
