### ISSUE TITLE
steambot issue :/

### ISSUE THREAD

**Issue by xNexis** [felixge/node-mysql#1184]
```
connected
encrypt request
handshake complete
Logged in!
C:\Users\Administrator\Desktop\Bot\Bot\node_modules\mysql\lib\protocol\Parser.js:82
        throw err;
              ^
ReferenceError: item is not defined
    at Query._callback (C:\Users\Administrator\Desktop\Bot\Bot\tradebot.js:418:18)
    at Query.Sequence.end (C:\Users\Administrator\Desktop\Bot\Bot\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (C:\Users\Administrator\Desktop\Bot\Bot\node_modules\mysql\lib\protocol\sequences\Query.js:144:8)
    at Query.EofPacket (C:\Users\Administrator\Desktop\Bot\Bot\node_modules\mysql\lib\protocol\sequences\Query.js:128:8)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\Bot\Bot\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (C:\Users\Administrator\Desktop\Bot\Bot\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (C:\Users\Administrator\Desktop\Bot\Bot\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\Bot\Bot\node_modules\mysql\lib\Connection.js:96:28)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
```
someone knows why ?

**Comment by dougwilson** [comment]
Hi @xNexis ! So unfortinately this error won't be anything we could help you with, as it's not related to this module :(

The error is saying that in your file `C:\Users\Administrator\Desktop\Bot\Bot\tradebot.js` on line 418, you are trying to use a variable named `item`, but you never declared it (though `var item`).
