### ISSUE TITLE
ECONNRESET not triggering error event on connection

### ISSUE THREAD

**Issue by jasonkarns** [felixge/node-mysql#1207]
The following error is being thrown when our database fails over to a backup instance. Our first attempt to handle the error was to listen for `error` on each connection. However, this particular error is not being emitted on the connection, so our listener is never being invoked for us to handle.

Unfortunately, we're stuck on 2.0.1 (because we're stuck on a fork of Sequelize 1.6.0-beta4). Does anyone have any guidance on why this exception is being thrown and not emitted on the connection object?

```
Error: read ECONNRESET
    at errnoException (net.js:905:11)
    at TCP.onread (net.js:559:19)
    --------------------
    at Protocol._enqueue (/opt/apps/shutterstock-absinthe/deployment/node_modules/mysql/lib/protocol/Protocol.js:110:26)
    at Connection.query (/opt/apps/shutterstock-absinthe/deployment/node_modules/mysql/lib/Connection.js:148:25)
    at module.exports.Query.run (/opt/apps/shutterstock-absinthe/deployment/node_modules/sequelize/lib/dialects/mysql/query.js:26:17)
    at module.exports.execQueueItem (/opt/apps/shutterstock-absinthe/deployment/node_modules/sequelize/lib/dialects/mysql/connector-manager.js:226:21)
    at /opt/apps/shutterstock-absinthe/deployment/node_modules/sequelize/lib/dialects/mysql/connector-manager.js:180:25
    at adjustCallback (/opt/apps/shutterstock-absinthe/deployment/node_modules/sequelize/node_modules/generic-pool/lib/generic-pool.js:187:7)
    at dispense (/opt/apps/shutterstock-absinthe/deployment/node_modules/sequelize/node_modules/generic-pool/lib/generic-pool.js:211:9)
    at Object.me.acquire (/opt/apps/shutterstock-absinthe/deployment/node_modules/sequelize/node_modules/generic-pool/lib/generic-pool.js:260:5)
    at module.exports.enqueue (/opt/apps/shutterstock-absinthe/deployment/node_modules/sequelize/lib/dialects/mysql/connector-manager.js:171:19)
    at module.exports.ConnectorManager.query (/opt/apps/shutterstock-absinthe/deployment/node_modules/sequelize/lib/dialects/mysql/connector-manager.js:69:15)
    at module.exports.Sequelize.query (/opt/apps/shutterstock-absinthe/deployment/node_modules/sequelize/lib/sequelize.js:149:34)
    at null.fct (/opt/apps/shutterstock-absinthe/deployment/node_modules/sequelize/lib/query-interface.js:256:38)
    at null._onTimeout (/opt/apps/shutterstock-absinthe/deployment/node_modules/sequelize/lib/emitters/custom-event-emitter.js:15:16)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

**Comment by dougwilson** [comment]
Hi! This is just how this module works, unfortunately: when the error occurs during a command (`.query` in the case of that stack trace), we do not emit the error on the connection, but rather only as the `err` to the `callback` function in your `.query` call.

We could potentially add support to also emit the error on the connection if you have a listener attached, but that won't help you, since you'd have to upgrade the `mysql` module.

**Comment by jasonkarns** [comment]
My first attempt was to use the `validate` callback on the pool. Sequelize is using generic-pool, which has a validate hook that can declare a connection dead before it's acquired from the pool. However, the validate method must be synchronous and I believe `connection.ping()` is about the only way to truly validate the connection.

Right now I'm looking into monkey-patching the connection's `query` method to emit any error event on the connection as well.
