### ISSUE TITLE
Problem to get connection without internet.

### ISSUE THREAD

**Issue by bloudman** [felixge/node-mysql#1215]
I've got this error when i'm disconected from internet:

Debugger listening on port 5858
error connecting: Error: getaddrinfo ENOENT
    at Object.exports._errnoException (util.js:746:11)
    at errnoException (dns.js:49:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
    --------------------
    at Protocol._enqueue (C:\Users\Adrien\documents\visual studio 2015\Projects\stormhost\stormhost\node_modules\mysql\lib\protocol\Protocol.js:135:48)
    at Protocol.handshake (C:\Users\Adrien\documents\visual studio 2015\Projects\stormhost\stormhost\node_modules\mysql\lib\protocol\Protocol.js:52:41)
    at Connection.connect (C:\Users\Adrien\documents\visual studio 2015\Projects\stormhost\stormhost\node_modules\mysql\lib\Connection.js:123:18)
    at Object.<anonymous> (C:\Users\Adrien\documents\visual studio 2015\Projects\stormhost\stormhost\server.js:17:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.runMain [as _onTimeout] (module.js:501:10)
    at Timer.listOnTimeout (timers.js:119:15)

I don't understand why because my MySql server is on localhost

**Comment by sidorares** [comment]
@bloudman see #1030 and https://github.com/nodejs/node-v0.x-archive/issues/25338

**Comment by bloudman** [comment]
Thanks, i replaced "localhost" by 127.0.0.1 and it works fine!
