### ISSUE TITLE
Parser.js:82

### ISSUE THREAD

**Issue by ze21038** [felixge/node-mysql#1227]
hello,

im getting this error "
C:\Users\José\Downloads\Bot>node tradebot.js
connected
encrypt request
handshake complete
Logged in!
C:\Users\Jos├®\Downloads\Bot\node_modules\mysql\lib\protocol\Parser.js:82
        throw err;
        ^

ReferenceError: item is not defined
    at Query._callback (C:\Users\Jos├®\Downloads\Bot\tradebot.js:419:18)
    at Query.Sequence.end (C:\Users\Jos├®\Downloads\Bot\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (C:\Users\Jos├®\Downloads\Bot\node_modules\mysql\lib\protocol\sequences\Query.js:144:8)
    at Query.EofPacket (C:\Users\Jos├®\Downloads\Bot\node_modules\mysql\lib\protocol\sequences\Query.js:128:8)
    at Protocol._parsePacket (C:\Users\Jos├®\Downloads\Bot\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (C:\Users\Jos├®\Downloads\Bot\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (C:\Users\Jos├®\Downloads\Bot\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (C:\Users\Jos├®\Downloads\Bot\node_modules\mysql\lib\Connection.js:96:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)

C:\Users\José\Downloads\Bot>pause
Press any key to continue . . ."

can you help me ?

its because im running it under windows and it should be linux?

**Comment by dougwilson** [comment]
Hi! This I an error coming from your code. The error is coming from Downloads\Bot\tradebot.js lin 419. It says ReferenceError: item is not defined. This means that if you look on that line, you will see "item" used, but you forgot to declare that variable.

**Comment by ze21038** [comment]
wow thanks that solved m y problem :D 

now im getting this 


C:\Users\José\Downloads\Bot>node tradebot.js
connected
encrypt request
handshake complete
Logged in!
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\Users\Jos├®\Downloads\Bot\node_modules\mysql\lib\protocol\Protocol.js:103:13)
    at Socket.<anonymous> (C:\Users\Jos├®\Downloads\Bot\node_modules\mysql\lib\Connection.js:102:28)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)

C:\Users\José\Downloads\Bot>pause
Press any key to continue . . .

it's because im running it on windows?

thanks

**Comment by dougwilson** [comment]
Hi! No, nothing in here is going to be "because you're running Windows"--this entire module was actually developed on Windows by a Windows developer.

The error `Connection lost: The server closed the connection.` means that while you were connected to your MySQL server, your MySQL actually closed the connection, likely due to the idle timeout being reached or something else.

**Comment by ze21038** [comment]
its there a option in cpanel or phpmyadmin to remove that timeout? it usually happens after a bit of time, and this is a bot for a website so it must be working 24/7

thanks for the help your support its amazzing , 

btw if you can add me on skype: capslockinf 

thanks agan

**Comment by dougwilson** [comment]
Hi @ze21038 , there is a setting to change the time, but you cannot disable it. I would recommend not even attempting to try to keep a long-lived connection open anyway, because any old "network blip" could kill your connection and you'd have the same problem.

I would recommend rewriting your code to use the connection pool (https://github.com/felixge/node-mysql#pooling-connections)
