### ISSUE TITLE
MYSQL Error Steam bot

### ISSUE THREAD

**Issue by bagda391** [felixge/node-mysql#1237]
Hey!
Ok so on my CS:GO Jackpot website, when pot reaches 50 items I get this error in the bot's console:

https://gyazo.com/ddff76265cae94236ed58a3e1c87801b

Also sometimes I get this error too:
```
Error: number format error: empty string
at Error (native)
at Function.Long.fromString (C:\Users\Frederik\Desktop\bot\node_modules\steam-tradeoffers\node_modules\long\dist\Long.js:180:19)
at toAccountId (C:\Users\Frederik\Desktop\bot\node_modules\steam-tradeoffers\index.js:376:15)
at SteamTradeOffers.makeOffer (C:\Users\Frederik\Desktop\bot\node_modules\steam-tradeoffers\index.js:396:42)
at Query._callback (C:\Users\Frederik\Desktop\bot\sell.js:160:13)
at Query.Sequence.end (C:\Users\Frederik\Desktop\bot\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
at Query._handleFinalResultPacket (C:\Users\Frederik\Desktop\bot\node_modules\mysql\lib\protocol\sequences\Query.js:144:8)
at Query.EofPacket (C:\Users\Frederik\Desktop\bot\node_modules\mysql\lib\protocol\sequences\Query.js:128:8)
at Protocol._parsePacket (C:\Users\Frederik\Desktop\bot\node_modules\mysql\lib\protocol\Protocol.js:271:23)
at Parser.write (C:\Users\Frederik\Desktop\bot\node_modules\mysql\lib\protocol\Parser.js:77:12)
```

Basically right now, I get an extra row in a table called queue when the bot gets the empty string error.
Any help please?

**Comment by bagda391** [comment]
The sell.js points to the queue to send the trade offer in the queue, but the queue row is missing the userid + token (so somehow I guess the userid + token are not converted properly?). Normally looks like https://gyazo.com/294266c90c1c7e5ae4a6b398b2454173 ,but when string error kicks in, there is no value for 2nd and 3rd column in db.

**Comment by dougwilson** [comment]
Hi @bagda391 , unfortinately all the stack traces provided here originate in your own code, which you have not posted. I probably wouldn't be able to provide much help without getting access to your full source code and a way to reproduce the issue in order to use standard debugging tools to diagnose your issue.

**Comment by bagda391** [comment]
@dougwilson I'll post the code in 3 hours

**Comment by bagda391** [comment]
@dougwilson here you go: http://pastebin.com/gLPLsp4s

**Comment by dougwilson** [comment]
I'm not seeing any code in there that does an INSERT into the `status` table. Is there more code still, or is this everything? Can you provide me instructions on what to do with that code to try and run it and provide instructions on how to reproduce the issue?

**Comment by bagda391** [comment]
Insert into "queue"

**Comment by dougwilson** [comment]
For some reason I just don't see it. What line number is it on?

**Comment by bagda391** [comment]
Oh forgot: http://pastebin.com/Gn3xqjDZ 
I have this on website that inserts into queue.

**Comment by dougwilson** [comment]
Hi @bagda391 , if your issue is missing data in the `queue` table and the only thing inserting into that table is PHP, I'm not quite sure how this module comes into play. Unfortunately I do not know PHP, so I do not have a way to really help much further, especially since you still haven't provided full instructions on how I'm supposed to run the code and reproduce the issue.

**Comment by bagda391** [comment]
@dougwilson oh :/ sorry ^^
