### ISSUE TITLE
`Error: Handshake inactivity timeout` in Node v4.2.0

### ISSUE THREAD

**Issue by adam8810** [felixge/node-mysql#1238]
Just updated Node to v4.2.0 and started to receive this exception.

```events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Handshake inactivity timeout
    at Handshake.<anonymous> (/Users/Adam/bin/project/node_modules/mysql/lib/protocol/Protocol.js:154:17)
    at emitNone (events.js:67:13)
    at Handshake.emit (events.js:166:7)
    at Handshake._onTimeout (/Users/Adam/bin/project/node_modules/mysql/lib/protocol/sequences/Sequence.js:116:8)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by adam8810** [comment]
Duplicate of #1236. Sorry about that.

**Comment by dougwilson** [comment]
It's no problem! Just upgrade Node.js to 4.2.1 :)

**Comment by vijayviji** [comment]
+1
