### ISSUE TITLE
this.disconnected(); ERROR

### ISSUE THREAD

**Issue by onsamp** [felixge/node-mysql#1303]
```js
mysql.createPool({
        connectionLimit: 100,
        host: 'localhost',
        user: 'root',
        password: 'pass',
        database: 'name'
    });
```

```
c:\Users\nfs_b\Desktop\obmen-box\node_modules\mysql-connection-manager\lib\index.js:299
					this.disconnected();
					     ^

TypeError: this.disconnected is not a function
    at Ping._callback (c:\Users\nfs_b\Desktop\obmen-box\node_modules\mysql-connection-manager\lib\index.js:299:11)
    at Ping.Sequence.end (c:\Users\nfs_b\Desktop\obmen-box\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Protocol.handleNetworkError (c:\Users\nfs_b\Desktop\obmen-box\node_modules\mysql\lib\protocol\Protocol.js:358:14)
    at Connection._handleNetworkError (c:\Users\nfs_b\Desktop\obmen-box\node_modules\mysql\lib\Connection.js:384:18)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)
    at doNTCallback2 (node.js:452:9)
    at process._tickCallback (node.js:366:17)
 ```

**Comment by dougwilson** [comment]
Hi! We have no method named `disconnected()` in our API, so ultimately the bug is in the file `c:\Users\nfs_b\Desktop\obmen-box\node_modules\mysql-connection-manager\lib\index.js`, which is not part of this module. You'll need to file a bug in their issue tracker: https://github.com/chill117/mysql-connection-manager
