### ISSUE TITLE
Fatal error with connection handling: 'PROTOCOL_CONNECTION_LOST'

### ISSUE THREAD

**Issue by wesleygauntt** [felixge/node-mysql#1304]
Hey All,

Been struggling with an ongoing issue related to connections and sql. In using the most recent version of node-sql (using current head of github module), we receive the following error on a daily basis. 

`[Error: Connection lost: The server closed the connection.] fatal: true, code: 'PROTOCOL_CONNECTION_LOST'`

This leads to a fatal error (see more below). In our SQL logs, we see that our server disconnected, however there are no errors. We are using mariadb v5.5.44 as well to handle our sql databases with mostly default settings. We upped the number of connections to 500, though it did not solve our issue. Our server and its connections are built to try and stay alive at all times, and we are currently handling connections with the following code:

    function setupMysqlConnection(req, res, next){

      log.debug("Setting up sql connection.");
      req = req || {};
      req.sqlConnection = mysql.createConnection(dbconfig.connection);
      req.sqlConnection.on('error', function(err){
          log.warn('On SQL connection error: ', err);
          if(!err.fatal)
              return;
          if(err.code !== 'PROTOCOL_CONNECTION_LOST')
              throw err;

          log.info("Attempting to re-connect with SQL.");
          setupMysqlConnection();
      });

      req.sqlConnection.connect(function(err){
          if(err){
              log.warn('Error connecting to SQL: ', err);
              log.info("Attempting to re-connect with SQL.");
              setTimeout(setupMysqlConnection, 2000);
          }
          log.debug('Connected to sql with ID: ', req.sqlConnection.threadId);
      });
      req.sqlConnection.query('USE ' + dbconfig.database);

      req.on('end', function(){
          //Give some time to process outstanding async sql queries, then close connection
          setTimeout(function(){
              var connectionId = this.sqlConnection.threadId;
              // this.sqlConnection.end(function(err){
              //     if(err){
              //       log.warn("Error on ending sql connection: ", err);
              //     }
              //     log.debug('Sql connection closed for ID: ' + connectionId);
              // });
              this.sqlConnection.destroy();
          }.bind(this), 5000);
      });
    }

Above has been modeled after other solutions to this issue:
http://stackoverflow.com/questions/20210522/nodejs-mysql-error-connection-lost-the-server-closed-the-connection

The above posted code does attempt to try and recreate a connection if a connection is ever lost. It seemed as if `sqlConnection.destroy()` seemed to let our server stay alive longer than `sqlConnection.end()`, though errors still show regardless of the method of connection closing. In addition to the output of the top error, we also get an additional which causes our server to crash:

    {"msg":"Attempting to re-connect with SQL.","time":"2015-12-09T00:46:20.152Z","v":0}
    {"msg":"Setting up sql connection.","time":"2015-12-09T00:46:20.152Z","v":0}
    {"msg":"Caught exception: TypeError: req.on is not a function","time":"2015-12-09T00:46:20.250Z","v":0}
    {"msg":"Caught exception: TypeError: req.on is not a function","time":"2015-12-09T00:46:20.250Z","v":0}
    Trace: [TypeError: req.on is not a function]
        at process.<anonymous> (/src/server.js:62:11)
        at emitOne (events.js:82:20)
        at process.emit (events.js:169:7)
        at process._fatalException (node.js:223:26)
    Trace: [TypeError: req.on is not a function]
    at process.<anonymous> (/src/server.js:62:11)
    at emitOne (events.js:82:20)
    at process.emit (events.js:169:7)
    at process._fatalException (node.js:223:26)
    freetype.js:1

In looking at past issues, connection pooling was suggested as a solution. We attempted to use the following code to handle connection pooling, but unfortunately it led to the same above errors:

    var pool  = mysql.createPool({
      connectionLimit : 1000,
      host     : dbconfig.connection.host,
      user     : dbconfig.connection.user,
      password : dbconfig.connection.password,
      database : dbconfig.database,
      ssl: dbconfig.connection.ssl
    });

    function setupMysqlConnection(req, res, next){

      log.debug("Setting up sql connection.");
      req = req || {};

      //https://github.com/felixge/node-mysql#pooling-connections
      //SQL Connection pooling code.

      log.debug("Setting up sql connection.");

      pool.getConnection(function(err, connection) {
        if(err)
          log.warn("Error getting pool connection: ", err);
        req.sqlConnection = connection;
        next();
      });

      pool.on('connection', function (connection) {
        log.debug('Connected with threadId: ', connection.threadId);
      });

      pool.on('enqueue', function () {
        log.info('Waiting for available connection slot');
      });

      req.on('end', function(){
          //Give some time to process outstanding async sql queries, then close connection
          setTimeout(function(){
            var connectionId = this.sqlConnection.threadId;
            log.info("Releasing connectionId: ", connectionId);
            this.sqlConnection.release(function(err){
              if(err)
                log.warn("Error releasing sql connection: ", err);
              else
                log.debug('Sql connection released for threadId: ' + connectionId);
            });
          }.bind(this), 5000);
      });
    }

Our server does maintain consistent traffic as we have a bot that pings a status route which tests our connections to sql. If more information is needed I'd be happy to post it. Thank you!

**Comment by wesleygauntt** [comment]
There are two parts of the problem here, and I believe neither are the fault for this plugin, so I will mark this issue as closed.

For reference for anyone else who may have this issue:

The first issue -- The SQL server goes down (errors, memory leaks, server shutdown etc.) This could be due to something in your code, sql setup or a different environmental issue.

The second issue which gave the .on errors above, was not calling the recursive function with parameters. Check out the code below:
```js
    req.sqlConnection.on('error', function(err){
      log.warn('On SQL connection error: ', err);
      if(!err.fatal)
          return;
      if(err.code !== 'PROTOCOL_CONNECTION_LOST')
          throw err;
  
      log.info("Attempting to re-connect with SQL.");
      // This is what was previously in there
      // setupMysqlConnection();

      // And this is what it should have been
      setupMysqlConnection(req, res, next);
    });
```

Now a few things to note: 

1. If your sql server is off or down, this function will keep spinning recursively waiting for a connection. This might cause some problems depending on how long your server is off. The solution here would be to add some limiting param to prevent an infinite loop.

2. After adding the params to `setupMysqlConnection`, both the individual connection and connection pooling methods worked. If choosing connection pooling using the original pooling code above, you'll need to add some error handling as follows:

```js
      pool.getConnection(function(err, connection) {
        if(err){
          log.warn("Error getting pool connection: ", err);
          log.info("Attempting to re-connect with SQL.");
          setupMysqlConnection(req, res, next);
          return;
        }
        req.sqlConnection = connection;
        next();
      });
```

Hope this helps! If anything comes up I'll update the issue -- Thanks!
