### ISSUE TITLE
"SyntaxError: Unexpected end of input"  if Query Contains 'WHERE'

### ISSUE THREAD

**Issue by okierie** [felixge/node-mysql#1305]
Hi, everyone! <br>I have a question. Please, take a look at my script:
```javascript
var dbconn = mysql.createConnection({
    host     : 'localhost',
    user     : 'root',
    password : '123',
    database : 'mydb'
});
var query   = dbconn.query("SELECT * FROM m02serials WHERE SerialNumber = '"+serialnumber+"'");
```
There is no error hints shown on my IDE for the above script. But, There is an error message just after the above line:
```
SyntaxError: Unexpected end of input
    at Object.exports.createScript (vm.js:24:10)
    at REPLServer.defaultEval (repl.js:137:25)
    at bound (domain.js:250:14)
    at REPLServer.runBound [as eval] (domain.js:263:12)
    at REPLServer.<anonymous> (repl.js:393:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:210:10)
    at REPLServer.Interface._line (readline.js:549:8)
    at REPLServer.Interface._ttyWrite (readline.js:884:20)
``` 
**The above error message doesn't appear if I only write `SELECT * FROM m02serials` query (without `WHERE`)**. But, I want to put `WHERE` in the query.<br>
How is the right script to do this?

**Comment by okierie** [comment]
It's my bad!
It's only need to change the `single quotes` with `double quotes`.
So the script is like:
```javascript
var query   = dbconn.query("SELECT * FROM m02serials WHERE SerialNumber = \""+serialnumber+"\"");
```
I think this issue have to be closed. Thanks.
