### ISSUE TITLE
Empty GEOMETRY data.buffer() returns null

### ISSUE THREAD

**Issue by sushantdhiman** [felixge/node-mysql#1310]
Whenever I try to parse the empty `GEOMETRY` data like ``{ type: 'Point', coordinates: []' }`` it will give me error like this on calling the `parseGeometryValue()`.

```
RangeError: index out of range
    at checkOffset (buffer.js:506:11)
    at Buffer.readUInt32BE (buffer.js:580:5)
    at parseGeometry (/var/www/html/github/sequelize/node_modules/mysql/lib/protocol/Parser.js:320:67)
    at Parser.parseGeometryValue (/var/www/html/github/sequelize/node_modules/mysql/lib/protocol/Parser.js:363:10)
    at Object.GEOMETRY.parse.GEOMETRY.parse [as GEOMETRY] (/var/www/html/github/sequelize/lib/dialects/mysql/data-types.js:66:33)
    at ConnectionManager.$typecast (/var/www/html/github/sequelize/lib/dialects/mysql/connection-manager.js:44:33)
    at RowDataPacket.parse (/var/www/html/github/sequelize/node_modules/mysql/lib/protocol/packets/RowDataPacket.js:33:24)
    at Query.RowDataPacket (/var/www/html/github/sequelize/node_modules/mysql/lib/protocol/sequences/Query.js:148:10)
    at Protocol._parsePacket (/var/www/html/github/sequelize/node_modules/mysql/lib/protocol/Protocol.js:244:14)
    at Parser.write (/var/www/html/github/sequelize/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/var/www/html/github/sequelize/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/var/www/html/github/sequelize/node_modules/mysql/lib/Connection.js:96:28)
```
for returned result the `results.buffer()` will be empty. There is complete loss on what kind of `GEOM ETRY` data has been returned.

Is there any way to know type of `GEOMETRY` data even when the contents are `null`? Is this a bug?

**Comment by dougwilson** [comment]
Hi! Since you are using `typeCast`, you are getting exactly what the MySQL server is sending over the wire. To me, this sounds like no issue on this module, as your MySQL server is sending you a NULL for the column value and we are simply providing that to you (we provide no transformations from `typeCast`, only the direct over-the-wire representations the MySQL server is returning). If you want me to take a look and confirm that MySQL is providing a NULL value for sure, please provide the following information:

1. Version of MySQL server you are using.
2. Version of Node.js you are using.
3. Version of this module you are using.
4. SQL to create a table to use to reproduce the issue.
5. SQL to insert data into that table.
6. A script that only uses this module and reproduces the issue (the script should pretty much just look like the example at https://github.com/felixge/node-mysql#introduction)--it should not use `sequelize` as part of the reproduction.

**Comment by sushantdhiman** [comment]
This issue is appearing because there is no support for `POINT EMPTY` in MySQL yet https://dev.mysql.com/worklog/task/?id=2381, MySQL stores `NULL` for invalid geometry data for now.

But `node-mysql` is doing the correct thing by returning the `NULL` as stored in database. Thus this is not a bug with the library.
