### ISSUE TITLE
Error when connecting to MySQL DB

### ISSUE THREAD

**Issue by 3thanZ** [felixge/node-mysql#1321]
Hi,

I am using the numtel/meteor-mysql package which uses this package as the underlying connector to a MySQL database. When connecting to the database, I receive the error: **`TypeError: Column must be greater than or equal to 0, got -14`**

```
  var mysql = require('mysql');

  var self = this;
  var db = mysql.createConnection({
	host: 'localhost',
	user: 'redmine',
	password: 'redmine',
	database: 'redmine',
	serverId: 1,
	minInterval: 200
  });

  self.db.connect(function(error) {
    ...
  });
```

MySQL version:
```
$ ./mysql --version
./mysql  Ver 14.14 Distrib 5.5.38, for osx10.6 (i386) using  EditLine wrapper
```

**Please advise on the possible cause and resolution of the problem. Thank you**

Stacktrace:
```
W20160107-15:34:23.430(8)? (STDERR) /Users/ethans/.meteor/packages/numtel_mysql/.1.0.3.u1roy7++os+web.browser+web.cordova/npm/node_modules/mysql/lib/protocol/Parser.js:82
W20160107-15:34:23.431(8)? (STDERR)         throw err;
W20160107-15:34:23.431(8)? (STDERR)               ^
W20160107-15:34:23.449(8)? (STDERR) TypeError: Column must be greater than or equal to 0, got -14
W20160107-15:34:23.450(8)? (STDERR)     at SourceMapConsumer_findMapping [as _findMapping] (/Users/ethans/.meteor/packages/meteor-tool/.1.1.10.1nmjijv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/source-map/lib/source-map/source-map-consumer.js:281:15)
W20160107-15:34:23.450(8)? (STDERR)     at SourceMapConsumer_originalPositionFor [as originalPositionFor] (/Users/ethans/.meteor/packages/meteor-tool/.1.1.10.1nmjijv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/source-map/lib/source-map/source-map-consumer.js:310:26)
W20160107-15:34:23.450(8)? (STDERR)     at mapSourcePosition (/Users/ethans/.meteor/packages/meteor-tool/.1.1.10.1nmjijv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/source-map-support/source-map-support.js:160:42)
W20160107-15:34:23.451(8)? (STDERR)     at wrapCallSite (/Users/ethans/.meteor/packages/meteor-tool/.1.1.10.1nmjijv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/source-map-support/source-map-support.js:295:20)
W20160107-15:34:23.451(8)? (STDERR)     at wrapCallSite (/Users/ethans/Desktop/dk/dk-int-projects-tracker/trunk/src/.meteor/local/build/programs/server/boot.js:75:15)
W20160107-15:34:23.451(8)? (STDERR)     at /Users/ethans/.meteor/packages/meteor-tool/.1.1.10.1nmjijv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/source-map-support/source-map-support.js:330:26
W20160107-15:34:23.451(8)? (STDERR)     at Array.map (packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:448:1)
W20160107-15:34:23.451(8)? (STDERR)     at Function.prepareStackTrace (/Users/ethans/.meteor/packages/meteor-tool/.1.1.10.1nmjijv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/source-map-support/source-map-support.js:329:24)
W20160107-15:34:23.451(8)? (STDERR)     at Handshake.Sequence._addLongStackTrace (/Users/ethans/.meteor/packages/numtel_mysql/.1.0.3.u1roy7++os+web.browser+web.cordova/npm/node_modules/mysql/lib/protocol/sequences/Sequence.js:67:42)
W20160107-15:34:23.452(8)? (STDERR)     at Handshake.Sequence.end (/Users/ethans/.meteor/packages/numtel_mysql/.1.0.3.u1roy7++os+web.browser+web.cordova/npm/node_modules/mysql/lib/protocol/sequences/Sequence.js:78:10)
```

**Comment by dougwilson** [comment]
Hi! The error you provided is coming from `SourceMapConsumer_findMapping [as _findMapping] (/Users/ethans/.meteor/packages/meteor-tool/.1.1.10.1nmjijv++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/source-map/lib/source-map/source-map-consumer.js:281:15`, which is not a prt of our code base. The first line shows our source simply because we are re-throwing it and that's what Node.js does on a re-throw.

**Comment by 3thanZ** [comment]
Thanks @dougwilson .... I corrected the username and password combination and the error went away. Would have been nice to have received a proper error message. But like you mentioned, it is an error from a different project. Cheers.

**Comment by dougwilson** [comment]
Indeed it would. Looking at the stack trace there shows we are giving an error from this module, likely a bad user/pass error. Unfortunately there is a bug in that other code somewhere that then has an error and so doesn't show ours :/
