### ISSUE TITLE
Get Error when Insert 1M rows from .sql file

### ISSUE THREAD

**Issue by terrywong2** [felixge/node-mysql#1322]
```
{ [Error: Packets out of order. Got: 3 Expected: 5] code: 'PROTOCOL_PACKETS_OUT_OF_ORDER', fatal: true }
```

any ideas?

**Comment by dougwilson** [comment]
Hi! That stack trace is for a different module, mysql2.

**Comment by dougwilson** [comment]
Apparently you completely altered the text from your original post. There is no longer enough context to be able to help. Can you provide a stack trace, version of this module, version of Node.js, and a way to reproduce?

**Comment by terrywong2** [comment]
Hi!
I am trying node-mysql and node-mysql2, so it makes me confused, sorry about it.
The code is run on nodejs v5.0.0 and use the node-mysql 2.10.0 module.

```
```
Trace
    at Query._callback (/var/www/public/benchmark/mysql-benchmark.js:71:33)
    at Query.Sequence.end (/var/www/public/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Protocol.handleParserError (/var/www/public/node_modules/mysql/lib/protocol/Protocol.js:373:14)
    at Parser.write (/var/www/public/node_modules/mysql/lib/protocol/Parser.js:47:14)
    at Protocol.write (/var/www/public/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/var/www/public/node_modules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
insert err:  { [Error: Packets out of order. Got: 3 Expected: 5] code: 'PROTOCOL_PACKETS_OUT_OF_ORDER', fatal: true }
```
here is my code:
<https://gist.github.com/terrywong2/95bf08fcdfaecc9cfad5>

Thanks!

**Comment by dougwilson** [comment]
THanks, @terrywong2 . The error is regarding the packets coming from the server that we think are out-of-order. Would you be willing to capture a trace of the packets with something like Wireshark, so we can take a look at it?

**Comment by terrywong2** [comment]
i figured out it is a mysql config problem, set `max_allowed_packet` the value to `1073741824` to solved this problem, but node-mysql shows the wrong message(?).

when `max_allowed_packet = 16M`, `max_allowed_packet = 32M`
{ [Error: Packets out of order. Got: 3 Expected: 5] code: 'PROTOCOL_PACKETS_OUT_OF_ORDER', fatal: true }

when `max_allowed_packet = 64M`
{ [Error: ER_NET_PACKET_TOO_LARGE: Got a packet bigger than 'max_allowed_packet' bytes]

when `max_allowed_packet >= 128M` works fine

Wireshark Captures:
`max_allowed_packet = 16M`
[mysql_16M_PROTOCOL_PACKETS_OUT_OF_ORDER.pcapng.zip](https://github.com/felixge/node-mysql/files/83221/mysql_16M_PROTOCOL_PACKETS_OUT_OF_ORDER.pcapng.zip)

`max_allowed_packet = 32M`
[mysql_32M_PROTOCOL_PACKETS_OUT_OF_ORDER.pcapng.zip](https://github.com/felixge/node-mysql/files/83224/mysql_32M_PROTOCOL_PACKETS_OUT_OF_ORDER.pcapng.zip)

`max_allowed_packet = 64M`
[mysql_64M_ER_NET_PACKET_TOO_LARGE.pcapng.zip](https://github.com/felixge/node-mysql/files/83223/mysql_64M_ER_NET_PACKET_TOO_LARGE.pcapng.zip)

ref:
<https://bugs.mysql.com/bug.php?id=53902>
<http://dev.mysql.com/doc/refman/5.5/en/server-system-variables.html#sysvar_max_allowed_packet>
