### ISSUE TITLE
ReferenceError: err is not defined

### ISSUE THREAD

**Issue by jublo** [felixge/node-mysql#1333]
How to fix this?

```
/myproject/node_modules/mysql/lib/protocol/Parser.js:77
        throw err; // Rethrow non-MySQL errors
        ^

ReferenceError: err is not defined
    at Query._callback (database.js:37:13)
    at Query.Sequence.end (/myproject/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query._handleFinalResultPacket (/myproject/node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
    at Query.OkPacket (/myproject/node_modules/mysql/lib/protocol/sequences/Query.js:78:10)
    at Protocol._parsePacket (/myproject/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/myproject/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/myproject/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/myproject/node_modules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
```

Calling code:

```javascript
  let dfd = q.defer();
  db.query(
    "UPDATE `markets` SET `rate` = ? WHERE `id` = ?",
    [rate, market.id],
    (error, results, fields) => {
      debug.log(1, error);
      debug.log(1, results);
      debug.log(1, fields);

      if (err) {
        dfd.reject(err);
        return;
      }
      dfd.resolve();
    }
  );
```

Version: 2.10.2
Node: v5.0.0

**Comment by jublo** [comment]
Found. It was a thrown Exception from my own code that got rerouted through your error handlers.

**Comment by dougwilson** [comment]
Hi @jublo, yep, you got it! Sorry for the confusion that Node.js creates when an error is re-thrown; the first line is the line of the `throw` vs the line of where the error occurred (the first one in the stack trace).

**Comment by Fuck-You-GFW** [comment]
I have the same issue. But I am still not knowing how to handle the exception. Is there anyone tell me?

**Comment by atif089** [comment]
^^ +1 same here...

This is happening when I throw an exception from inside a mysql.connection.query callback

**Comment by dougwilson** [comment]
You can't throw from inside callback functions in Node.js, since there is no way to catch it. Node.js only gives you two options:

1. Be very careful not to throw any errors.
2. Wrap the full contents of your callback function body in a try-catch.

**Comment by atif089** [comment]
Strange, I don;t understand why does it work in some cases..

**Comment by bitsofinfo** [comment]
@atif089  how did you solve your problem, I am having the same issue. ....

**Comment by atif089** [comment]
@bitsofinfo it was not a problem in the library. It was a problem in my code. However, I don't know why it shows like it's a problem with Mysql.

Check your code, and follow what @dougwilson replied.

**Comment by luantoni** [comment]
Hi
