### ISSUE TITLE
Problem with Long.js

### ISSUE THREAD

**Issue by Celestriall** [felixge/node-mysql#1335]
```
 /var/www/bot/node_modules/steam-tradeoffers/node_modules/long/dist/Long.js:203
        if (str.length === 0)
               ^
TypeError: Cannot read property 'length' of undefined
    at Function.fromString (/var/www/bot/node_modules/steam-tradeoffers/node_modules/long/dist/Long.js:203:16)
    at toAccountId (/var/www/bot/node_modules/steam-tradeoffers/index.js:362:15)
    at SteamTradeOffers.getHoldDuration (/var/www/bot/node_modules/steam-tradeoffers/index.js:64:42)
    at /var/www/bot/bot.js:762:42
    at SteamTradeOffers.<anonymous> (/var/www/bot/node_modules/steam-tradeoffers/index.js:429:7)
    at Request.self.callback (/var/www/bot/node_modules/steam-tradeoffers/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/var/www/bot/node_modules/steam-tradeoffers/node_modules/request/request.js:1035:10)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/var/www/bot/node_modules/steam-tradeoffers/node_modules/request/request.js:962:12)
```
Anyone knows a solution for this please?

**Comment by dougwilson** [comment]
Hi @Celestriall! So the issue is that there is a problem either in your code on line 762 file `/var/www/bot/bot.js`, or a bug in the `steam-tradeoffers` module.

Unfortunately none of the stack trace is even in the MySQL module here, so I'm not really able to help from a MySQL point of view :(
