### ISSUE TITLE
Error on CSGO Jackpot bot

### ISSUE THREAD

**Issue by sonicvinyes** [felixge/node-mysql#1342]
When I receive a trade offer, my bot crash and says this error:
Who I can run my bot without errors?

[https://gyazo.com/97e853f1309f09175376e5323548958d](url)
```
C:\Users\Javi\Desktop\JACKPOTBOT\node_modules\mysql\lib\protocol\Parser.js:82
        throw err;
        ^

TypeError: Cannot read property 'value' of undefined
    at Query._callback (C:\Users\Javi\Desktop\JACKPOTBOT\sell.js:573:23)
    at Query.Sequence.end (C:\Users\Javi\Desktop\JACKPOTBOT\node_modules\mysql\l
ib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (C:\Users\Javi\Desktop\JACKPOTBOT\node_mod
ules\mysql\lib\protocol\sequences\Query.js:144:8)
    at Query.EofPacket (C:\Users\Javi\Desktop\JACKPOTBOT\node_modules\mysql\lib\
protocol\sequences\Query.js:128:8)
    at Protocol._parsePacket (C:\Users\Javi\Desktop\JACKPOTBOT\node_modules\mysq
l\lib\protocol\Protocol.js:271:23)
    at Parser.write (C:\Users\Javi\Desktop\JACKPOTBOT\node_modules\mysql\lib\pro
tocol\Parser.js:77:12)
    at Protocol.write (C:\Users\Javi\Desktop\JACKPOTBOT\node_modules\mysql\lib\p
rotocol\Protocol.js:39:16)
    at Socket.<anonymous> (C:\Users\Javi\Desktop\JACKPOTBOT\node_modules\mysql\l
ib\Connection.js:96:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)

C:\Users\Javi\Desktop\JACKPOTBOT>pause
```

**Comment by dougwilson** [comment]
Hi @sonicvinyes, unfortunately this is just a coding mistake you made in your bot and not something I can help you with in regards to this module. The stack trace says that in file `C:\Users\Javi\Desktop\JACKPOTBOT\sell.js`, line 573, you are trying to access the property `value` on some object, but that objet is `undefined`.
