### ISSUE TITLE
RangeError: Invalid array buffer length

### ISSUE THREAD

**Issue by deepwell** [felixge/node-mysql#1415]
Ran into this unexpected error:

```
/home/user/app/node_modules/mysql/lib/protocol/Parser.js:15
  this._packetHeader      = null;
                               ^

RangeError: Invalid array buffer length
    at new ArrayBuffer (native)
    at new Uint8Array (native)
    at createBuffer (buffer.js:23:15)
    at allocate (buffer.js:98:12)
    at new Buffer (buffer.js:53:12)
    at Parser.append (/home/user/app/node_modules/mysql/lib/protocol/Parser.js:110:14)
    at Parser.write (/home/user/app/node_modules/mysql/lib/protocol/Parser.js:25:8)
    at Protocol.write (/home/user/app/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at TLSSocket.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
```
node v4.3.1
node-mysql 2.10.2

**Comment by dougwilson** [comment]
Weird, because there is no possible way that line can throw that error. Can you provide code and instructions on how to reproduce the error? What debugging have you done? Can you post what arguments are given to new Buffer when this happens?

**Comment by deepwell** [comment]
That's what I thought when looking at the code. I haven't been able to reproduce it and don't have any more debug info to give you. I simply saw it on production and took note of it.

If nothing can be done, feel free to close this issue. If I see this again I'll definitely add whatever info I can.
