### ISSUE TITLE
Getting error when receiving trade

### ISSUE THREAD

**Issue by SnipeCrane** [felixge/node-mysql#1424]
`C:\Users\hampa\Desktop\GoRoulette\bot\sell.js:490
                                                        if(offer.items_to_receive.length > row[0].value) {
                                                                                              ^

TypeError: Cannot read property '0' of undefined
    at Query._callback (C:\Users\hampa\Desktop\GoRoulette\bot\sell.js:490:46)
    at Query.Sequence.end (C:\Users\hampa\Desktop\GoRoulette\bot\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Protocol._validateEnqueue (C:\Users\hampa\Desktop\GoRoulette\bot\node_modules\mysql\lib\protocol\Protocol.js:218:6)
    at Protocol._enqueue (C:\Users\hampa\Desktop\GoRoulette\bot\node_modules\mysql\lib\protocol\Protocol.js:129:13)
    at Connection.query (C:\Users\hampa\Desktop\GoRoulette\bot\node_modules\mysql\lib\Connection.js:201:25)
    at C:\Users\hampa\Desktop\GoRoulette\bot\sell.js:489:23
    at Array.forEach (native)
    at C:\Users\hampa\Desktop\GoRoulette\bot\sell.js:481:41
    at Object.doAPICall.bind.callback (C:\Users\hampa\Desktop\GoRoulette\bot\node_modules\steam-tradeoffers\index.js:149:7)
    at SteamTradeOffers.<anonymous> (C:\Users\hampa\Desktop\GoRoulette\bot\node_modules\steam-tradeoffers\index.js:464:15)

C:\Users\hampa\Desktop\GoRoulette\bot>pause`

**Comment by kai-koch** [comment]
```row``` is not defined in that line.
Please check where ```row``` is defined and where ```row``` is used.
If you define ```row``` in a function (e.g. a callback-function) and try to use it outside of that function it is not defined.

Closed. Not a node-mysql problem.
