### ISSUE TITLE
Streaming a lot of rows throws RangeError

### ISSUE THREAD

**Issue by toddself** [felixge/node-mysql#918]
Using the streaming interface to read every row from a 12,586,398 row table causes the following error after 17,364 rows are processed. (Converting a MySQL key/val system to LevelDB)

```buffer.js:194
      this.parent = new SlowBuffer(this.length);
                    ^
RangeError: length > kMaxLength
    at new Buffer (buffer.js:194:21)
    at Parser.append (/root/src/scripto2/node_modules/mysql/lib/protocol/Parser.js:113:11)
    at Parser.write (/root/src/scripto2/node_modules/mysql/lib/protocol/Parser.js:25:8)
    at Protocol.write (/root/src/scripto2/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/root/src/scripto2/node_modules/mysql/lib/Connection.js:82:28)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at _stream_readable.js:781:16
    at process._tickCallback (node.js:419:13)
```

Code is calling `#pause` on each row and `#resume` when async processing is complete.

Code:

```js
 connection.query('SELECT * FROM store')
    .on('result', function(row){
      connection.pause();
      var data;

      var key = row.key;
      try {
        data = JSON.parse(row.value);
      } catch(e){
        console.log('Cannot parse', key, e);
        return;
      }

      db.put(key, data, function(err){
        if(err){
          console.log('cannot put', err);
          connection.destroy();
          db.close();
          process.exit(1);
        }
        process.stdout.write('.');
        connection.resume();
      });
    })
    .on('error', function(err){ console.log(err);})
    .on('field', function(){});
```

**Comment by dougwilson** [comment]
Hi @toddself , did you ever perform the test I asked above to see if the issue was resolved?

**Comment by toddself** [comment]
HI Doug!

Sorry I was unable to test out that last change -- the LIMIT and OFFSET method worked well enough that we were able to complete our data conversion and move away from mysql.

Thank you for your help!

**Comment by dougwilson** [comment]
No problem! Feel free to open a new issue if you ever run into this again!
