### ISSUE TITLE
Caught exception: TypeError: Cannot read property 'length' of undefined, on what seems to be big queries

### ISSUE THREAD

**Issue by dazaster** [felixge/node-mysql#958]
Hi,

I get an error when I process my query. 
I should get a array of 2500 records with 6 fields of data to each record.

I have created a module to enclose this and other things

This is my code snippet before it carries on responding the result and the I have debugged the rest of the code with process.exit(); The code works as I have 3 mysql queries ranging between 1 and 100 records return before the query that crashes it.

Example row that bugs it out
```
[ { x: 0, y: 0, built: 54, lastaction: 1363130316, company_id: -1 },
  { x: 1, y: 0, built: 54, lastaction: 1363130318, company_id: -1 },
  { x: 2, y: 0, built: 54, lastaction: 1363130317, company_id: -1 }]
```
x is 0-49, y is 0-49
the rest are pretty much the same all ints

I use mysql pooling for my connections, I have tried both the pooled connection and the single connection code commented out.

```javascript
var method = DB.prototype;

function DB( db_config) 
{
    this.mysqlmodule = require('mysql');
    this.db_config = db_config;
    this.dbArray = new Array();
    this.mysqlconn;
    
    //Init Connection
    this.handleDisconnect();
    
    var dbInstance = this;
    
    //Start Queue
    this.mysqlTimer();
}

//MYSQL DROP FUNCTION
method.handleDisconnect = function() {
    this.mysqlconn = this.mysqlmodule.createPool(this.db_config);
    var parent_class = this;
    /*this.mysqlconn = this.mysqlmodule.createConnection(this.db_config); // Recreate the connection, since
                                                    // the old one cannot be reused.

    this.mysqlconn.connect(function(err) {              // The server is either down
        if(err) {                                     // or restarting (takes a while sometimes).
            console.log('error when connecting to db:', err);
            setTimeout(parentClass.handleDisconnect, 2000); // We introduce a delay before attempting to reconnect,
        }                                     // to avoid a hot loop, and to allow our node script to
    });                                     // process asynchronous requests in the meantime.
                                            // If you're also serving http, display a 503 error.
    this.mysqlconn.on('error', function(err) {
        console.log('db error', err);
        if(err.code === 'PROTOCOL_CONNECTION_LOST') { // Connection to the MySQL server is usually
            parentClass.handleDisconnect();                         // lost due to either server restart, or a
        } else {                                      // connnection idle timeout (the wait_timeout
            throw err;                                  // server variable configures this)
        }
    });*/
};

method.query = function(statement, callback)
{
    if(typeof (callback) === 'undefined' )
    {
        callback = null;
    }
    var statementlist = { 'query': statement, 'callback': callback };
    
    this.dbArray.push(statementlist);
};

method.mysqlTimer = function()
{
    var arrayLength = this.dbArray.length;
    while(arrayLength--)
    {
        this.processmysql(this.dbArray[0]);
        this.dbArray.shift();
    }
    
    var dbInstance = this;
    setTimeout( function () { dbInstance.mysqlTimer(); }, 1000);
};
        
method.processmysql = function( statementlist )
{
    var query = statementlist.query;
    var callback = statementlist.callback;
    
    var parent_class = this;
    console.log("Hits This Prepend");
    //THIS FUNCTION CRASHES ON THE BIG QUERY
    this.mysqlconn.query(query, function(err, result)
    {
        //NEVER HITS AND TRIGGERS ANY OF THE FOLLOWING , ERROR OUTPUT BELOW
        console.log("Hits This");

        //HOWEVER I HAVE MADE IT WORK BY INSERTING THE CONSOLE LOG FOR RESULT, THIS IS NOT IDEAL :(
        //console.log(result);

        if( err !== null)
        {
            console.log("Hits This 1");
            parent_class.dbArray.push( statementlist );
            if(callback !== null)
            {
                callback(false);
            }
        }
        else
        {
            console.log("Hits This 2");
            if( callback !== null)
            {
                console.log("Hits This 3");
                callback(true, result);
            }
        }
    });
};

module.exports = DB;
``` 
Console Ouput 
```
Hits This Prepend
Caught exception: TypeError: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at RowDataPacket.parse (/var/nb/server/node_modules/mysql/lib/protocol/packets/RowDataPacket.js:28:35)
    at Protocol._parsePacket (/var/nb/server/node_modules/mysql/lib/protocol/Protocol.js:253:12)
    at Parser.write (/var/nb/server/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/var/nb/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/var/nb/server/node_modules/mysql/lib/Connection.js:82:28)
    at Socket.EventEmitter.emit (events.js:96:17)
    at Socket.<anonymous> (_stream_readable.js:720:14)
    at Socket.EventEmitter.emit (events.js:93:17)
    at emitReadable_ (_stream_readable.js:392:10)
    at emitReadable (_stream_readable.js:388:5)
```
The following output happens lots of times not sure how many I thought it might be one for every record, although this doesn't happen when not using the pooled connections
```
Caught exception: TypeError: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at RowDataPacket.parse (/var/nb/server/node_modules/mysql/lib/protocol/packets/RowDataPacket.js:28:35)
    at Protocol._parsePacket (/var/nb/server/node_modules/mysql/lib/protocol/Protocol.js:253:12)
    at Parser.write (/var/nb/server/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at process._tickCallback (node.js:415:13)
    at process._tickFromSpinner (node.js:390:15)
```

**Comment by scottp** [comment]
I also have this error but I have tracked it down. Error appears for 0.10.36 NodeJS and mysql@2.5.4. I had mistakenly selected the wrong database and the table I was querying did not exist. But the exception showing "TypeError: Cannot read property 'length' of undefined" was misleading. Once I commented out the trow, I actually got the following: "{code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","index":0}". The bug is therefore how the library is interpreting that error.

**Comment by dougwilson** [comment]
What throw did you comment out?

**Comment by scottp** [comment]
mysql/lib/protocol/Parser.js:82 
```
    try {
      this._onPacket(this._packetHeader);
      hadException = false;
    } catch (err) {
      if (!err || typeof err.code !== 'string' || err.code.substr(0, 7) !== 'PARSER_') {
        // Rethrow unknown errors
        throw err;
      }
```

**Comment by dougwilson** [comment]
@scottp can you post the stack trace for the error you got?

**Comment by scottp** [comment]
Yep...
```

/Users/scottp/1api/C-Config-API/node_modules/mysql/lib/protocol/Parser.js:82
        throw err;
              ^
TypeError: Cannot read property 'length' of undefined
    at Query._callback (/Users/scottp/1api/C-Config-API/routes/vendor.js:44:16)
    at Query.Sequence.end (/Users/scottp/1api/C-Config-API/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query.ErrorPacket (/Users/scottp/1api/C-Config-API/node_modules/mysql/lib/protocol/sequences/Query.js:93:8)
    at Protocol._parsePacket (/Users/scottp/1api/C-Config-API/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/Users/scottp/1api/C-Config-API/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/Users/scottp/1api/C-Config-API/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/scottp/1api/C-Config-API/node_modules/mysql/lib/Connection.js:82:28)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
```
Once I point to the correct database and schema it is fine. So the bug seems to be only how it is reporting errors (ie. the length is a red herring).

**Comment by dougwilson** [comment]
Yes, because we don't swallow errors from your code. All you did was hide the error on line 44 in your file routes/vendor.js that was accessing a length property.

**Comment by scottp** [comment]
So sorry. Completely my fault for misreading the stack backtrace. I had been chasing up another error todo with config all day and missed that. Aha. The error was this: 
```
if (err) res.json(err);
```
It should have been:
```
if (err) return res.json(err);
```
So the error was being hidden. So sorry.

**Comment by dougwilson** [comment]
@scottp it is no problem at all 😊
