### ISSUE TITLE
error connecting: Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by AlexRepeckiy** [felixge/node-mysql#975]
Hello, my node version 0.10.33. It s my code 
```js
var mysql = require('mysql');

var connection = mysql.createConnection({
  host     : 'localhost',
  user     : 'root',
  password : 'secret'
});

connection.connect(function(err) {
  if (err) {
    console.error('error connecting: ' + err.stack);
    return;
  }

  console.log('connected as id ' + connection.threadId);
});
```

```
error connecting: Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
    --------------------
    at Protocol._enqueue (/home/alexrepeckiy/web-project/soft-index/node_modules/mysql/lib/protocol/Protocol.js:135:48)
    at Protocol.handshake (/home/alexrepeckiy/web-project/soft-index/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at Connection.connect (/home/alexrepeckiy/web-project/soft-index/node_modules/mysql/lib/Connection.js:109:18)
    at Object.<anonymous> (/home/alexrepeckiy/web-project/soft-index/app.js:31:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

Help me pls.

**Comment by dougwilson** [comment]
It's a common issue. The problem is that you have no servers listening on TCP port 3306 on your localhost.

**Comment by dougwilson** [comment]
This old thread should help you: https://github.com/felixge/node-mysql/issues/874
